apiVersion: v1
kind: Pod
metadata:
  name: cool-pod
  labels:
    name: cool-pod
spec:
  containers:
    - name: cool-pod
      image: cool/pod:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: the-registry-secret # this secret must be created separately
