apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-share
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data
    server: eu-west-1b.fs-64HJku4i.efs.eu-west-1.amazonaws.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
    - name: test-pod
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: aws-efs
          mountPath: /mnt
  volumes:
    - name: aws-efs
      persistentVolumeClaim:
        claimName: efs
