apiVersion: v1
kind: Pod
metadata:
  name: hue-music
  labels:
    app: music
    service: music
spec:
  containers:
    - name: hue-music
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
          httpHeaders:
            - name: X-Custom-Header
              value: ItsAlive
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
