apiVersion: v1
kind: Pod
metadata:
  name: flocker-web
  labels:
    name: flocker-web
spec:
  containers:
    - name: flocker-web
      image: nginx
      ports:
        - name: web
          protocol: TCP
          containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: www-root
          mountPath: /usr/share/nginx/html
  volumes:
    - name: www-root
      flocker:
        datasetName: my-flocker-vol
