apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
type: kubernetes.io/rbd
data:
  key: QVFCMTZWMVZvRjVtRXhBQTVrQ1FzN2JCajhWVUxSdzI2Qzg0SEE9PQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: rbd2
  labels:
    name: rbd2
spec:
  containers:
    - name: rbd2
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: rbdpd
      rbd:
        image: foo
        pool: kube
        monitors:
          - "10.16.154.78:6789"
          - "10.16.154.82:6789"
          - "10.16.154.83:6789"
        readOnly: true
        fsType: ext4
        user: admin
        secretRef:
          name: ceph-secret
# Ceph RBD supports the ReadWriteOnce and ReadOnlyMany access modes.
