apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs
  labels:
    name: nginx-nfs
spec:
  containers:
    - name: nginx-nfs
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: test
          mountPath: /data
  volumes:
    - name: test
      flexVolume:
        driver: "k8s/nfs"
        fsType: nfs
        options:
          server: "1.1.1.1"
          share: "dws_nas_scratch"
