apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  fc:
    targetWWNs: ["50060e801049cfd1"]
    lun: 0
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pv
  labels:
    app: block-pv
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-block-pvc
  labels:
    name: pod-with-block-pvc
spec:
  containers:
    - name: pod-with-block-pvc
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeDevices:
        - name: data
          devicePath: /dev/data_device
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pv
