apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  containers:
    - name: hello-world
      image: hello/world:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  securityContext:
    privileged: true
    fsGroup: 1234
    supplementalGroups:
      - 5678
    seLinuxOptions:
      level: "s0:c123,c456"
