kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example
roleRef:
  kind: RoleBinding
  name: <role name>
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: custom-service-account
    namespace: default
  - kind: User # it's not recommended
    apiGroup: rbac.authorization.k8s.io
    name: mohammad_katoozi
  - kind: Group # only available in role binding not in the cluster role binding
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated # grant access to all authenticated users
