# Create a Services without Selectors
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1

---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.240.106.152
      - ip: 10.240.79.157
    ports:
      - name: http
        port: 1
        protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
  labels:
    name: some-pod
spec:
  containers:
    - name: some-pod
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: glusterfs-cluster
          mountPath: /mnt
  volumes:
    - name: glusterfs-vol
      glusterfs:
        path: kube_vol
        endpoints: glusterfs-cluster
        readOnly: true
