apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-of-pvc-1
  namespace: my-ns
  labels:
    app: clone-of-pvc-1
spec:
  storageClassName: clone
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-1
