apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
  namespace: default
  labels:
    app: restore-pvc
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: VolumeSnapshot
    name: new-snapshot-test
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 10Gi
