apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: container-with-secret
      image: g1g1/py-kube:0.2
      command: ["/bin/bash", "-c", "while true ; do sleep 10 ; done"]
      resources:
        limits:
          cpu: "250m"
          memory: 100Mi
      volumeMounts:
        - name: secret-volume
          mountPath: "/mnt/hush-hush"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: hush-hush
# create secret command: kubectl create secret generic hush-hush --from-literal=username=tobias --from-literal=password=cutoffs
