kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example
rules:
  - apiGroups: ["extensionspolicy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - <list of policies to authorize>
